name: geekbeard
favicon: null
layout_spectrum: 0.51534
typography_spectrum: 0.8166978443041444
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110916'
    - '#787878'
    - '#aaafb3'
    - '#3c3b40'
    - '#690d32'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.429468372836709
  rhythmicContrast: 0.7706259714905173
purpose: []
